import { BookingItem } from "@/app/types";

export const mockBookings: BookingItem[] = [
  {
    id: "1",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Monday",
    time: "00:00",
    type: "Flight",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "2",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Monday",
    time: "12:00",
    type: "Car",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "3",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Thursday",
    time: "12:00",
    type: "Flight",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "4",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Tuesday",
    time: "16:00",
    type: "Double",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "5",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Saturday",
    time: "14:00",
    type: "Double",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "6",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Sunday",
    time: "08:00",
    type: "Hotel",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "7",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Sunday",
    time: "20:00",
    type: "Flight",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "8",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Tuesday",
    time: "21:00",
    type: "Hotel",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
  {
    id: "9",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Saturday",
    time: "24:00",
    type: "Hotel",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
];

export const SingleMockBookings: Record<string, BookingItem> = {
  "1": {
    id: "1",
    userName: "Kemi Adeoti",
    timeRange: "12:00 - 12:45",
    day: "Monday",
    time: "00:00",
    type: "Flight",
    details: {
      firstName: "Kemi",
      lastName: "Adeoti",
      address: "12 Aliu Olaiya Avenue, Ikeja, Lagos State.",
      phone: "+234 8012 3456 789",
      email: "kemiadeoti@gmail.com",
      flight: {
        airline: "Air Peace Limited",
        departure: "Lagos (LOS)",
        arrival: "Abuja (ABV)",
        departureTime: "2:00pm",
        arrivalTime: "4:00pm",
        class: "Economy",
        ticketNumber: "1111",
        date: "Feb 9,2025",
        flightNumber: "P4 7120",
        duration: "2 Hrs",
        aircraft: "B737-700",
        price: {
          base: "₦50,000",
          taxes: "₦10,000",
          total: "₦110,000",
        },
      },
    },
  },
};

export const navItems = [
  {
    icon: "/assets/icons/side-dashboard.svg",
    label: "Dashboard",
    href: "/Dashboard",
    iconActive: "/assets/icons/a-sidebar-dashboard.svg",
  },
  {
    icon: "/assets/icons/Side-user.svg",
    label: "Users",
    href: "/Dashboard/user",
    iconActive: "/assets/icons/a-sidebar-user.svg",
  },
  {
    icon: "/assets/icons/side-booking.svg",   
    label: "Bookings",
    href: "/Dashboard/bookings",
    iconActive: "/assets/icons/a-sidebar-booking.svg",
  },
  {
    icon: "/assets/icons/side-cms.svg",
    label: "CMS",
    href: "/Dashboard/cms",
    iconActive: "/assets/icons/a-sidebar-cms.svg",
  },
  {
    icon: "/assets/icons/side-support.svg",
    label: "Customer Support",
    href: "/Dashboard/support",
    iconActive: "/assets/icons/a-sidebar-support.svg",
  },
  {
    icon: "/assets/icons/side-report.svg",
    label: "Report & Analytics",
    href: "/reports",
    iconActive: "/assets/icons/a-sidebar-report.svg",
  },
  {
    icon: "/assets/icons/side-roles.svg",
    label: "Admin Roles",
    href: "/Dashboard/admin",
    iconActive: "/assets/icons/a-sidebar-role.svg",
  },
];

export const ChartData = [
  { name: "Mon", Flight: 1, Hotel: 1, Car: 1 },
  { name: "Tue", Flight: 3.2, Hotel: 1, Car: 2.2 },
  { name: "Wed", Flight: 2.4, Hotel: 1.1, Car: 2.1 },
  { name: "Thu", Flight: 4.5, Hotel: 3.4, Car: 2.8 },
  { name: "Fri", Flight: 4.5, Hotel: 3.3, Car: 2.9 },
  { name: "Sat", Flight: 5, Hotel: 4.3, Car: 3.2 },
  { name: "Sun", Flight: 5.3, Hotel: 4, Car: 3.4 },
];
